### ISSUE TITLE
[k8]Shortlist which cloud provider

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/wordcount-k8#8]
Evaluate:
+ aws EKS
+ gcp GKE
+ azure AKS

**Comment by rpayal** [comment]
**AWS Fargate** - is a serverless compute engine for containers that works with both Amazon Elastic Container Service (ECS) and Amazon Elastic Kubernetes Service (EKS). Fargate removes the need to provision and manage servers, lets you specify and pay for resources per application, and improves security through application isolation by design.
Price
per vCPU per hour	$0.01237679
per GB per hour	$0.00135906

**AWS EKS** - You can run EKS on AWS using either EC2 or AWS Fargate, and on premises using AWS Outposts.
$0.10 per hour for each EKS cluster
- If used EC2 (including with EKS managed node groups), you pay for AWS resources (e.g. EC2 instances or EBS volumes) you create to run your Kubernetes worker nodes.
- If used AWS Fargate, pricing is calculated based on the vCPU and memory resources used from the time you start to download your container image until the Amazon EKS pod terminates, rounded up to the nearest second.

**Azure AKS**
1 yr free with new a/c ($250 credit for free)
Price
$0.10 per cluster per hour


**Google GKE** - Deploy, manage, and scale containerized applications on Kubernetes
1ye free with new a/c ($300 credit for free)
Price
$0.10 per cluster per hour

One zonal cluster (single-zone or multi-zonal) per billing account is free.

**Comment by rpayal** [comment]
All three AWS/Azure/Google charge $0.10 per cluster per hour.

Decided to go ahead with Azure AKS, created a 2 node cluster in AKS.

**Comment by nirmalchandra** [comment]
Azure shortlisted. Account created.
